apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - argocd-self.yaml
  - metallb.yaml
  - namespaces.yaml
  - nzbget.yaml
  - overseerr.yaml
  - plex.yaml
  - radarr.yaml
  - rookceph-install.yaml
  - rookceph.yaml
  - sonarr.yaml
  - twingate.yaml
