apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: overseerr-config
  namespace: plex
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: rook-cephfs
  resources:
    requests:
      storage: 10Gi
