apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: twingate
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
secretGenerator:
  - name: twingate-connector
    envs:
      - twingate-connector.env
generatorOptions:
  disableNameSuffixHash: true
