apiVersion: v1
kind: Service
metadata:
  name: nzbget
  namespace: plex
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.0.243
  selector:
    app: nzbget
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 6789
