apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../install
patches:
  - path: argocd-server-lb.yaml
    target:
      kind: Service
      name: argocd-server
  - path: argocd-cm-anon.yaml
    target:
      kind: ConfigMap
      name: argocd-cm
  - path: argocd-rbac-anon-admin.yaml
    target:
      kind: ConfigMap
      name: argocd-rbac-cm
